apiVersion: v1
kind: Pod
metadata:
  name: frn-flask-pod-v2
  labels:
    app: frn-flask-app-v2
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: flask-container
      image: localhost:5000/frn-flask-v2-tejaris-2025-07-07:v2
      ports: 
        - containerPort: 5000
      env:
        - name: REDIS_HOST
          value: "redis-service"
          
