FROM python:3.12-alpine
WORKDIR /app

RUN pip install --no-cache-dir flask==3.0.3 pandas==2.2.3 psycopg2-binary

COPY app.py .
COPY templates/ templates/
COPY static/ static/
COPY name.csv .

EXPOSE 5004

CMD ["python" , "app.py"]
