apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-db-flask-deployment
  namespace: name-db-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fp-name-db-app
  template:
    metadata:
      labels:
        app: fp-name-db-app
    spec:
      containers:
        - name: flask-app
          image: name-db-2026-07:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: flask-name-db-config
            
            - secretRef:
                name: flask-name-db-secret
