apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: name-db-statefulset
  namespace: name-db-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-db
  template:
    metadata:
      labels:
        app: name-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: name_db
            - name: POSTGRES_USER
              value: name_user
            - name: POSTGRES_PASSWORD
              value: name_pass
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
 #          - name: postgres-init-volume
 #            mountPath: /docker-entrypoint-initdb.d
 #              readOnly: true
            - name: postgres-data-volume
              mountPath: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: pvc-for-name-db
#       - name: postgres-init-volume
#         configMap:
#           name: name-db-postgres-init
