apiVersion: v1
kind: PersistentVolume
metadata:
  name: name-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
    #storageClassName: local-storage
  hostPath:
    path: /home/behroox/bixi_app_01

