apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-name-db
spec:
  capacity:
    storage: 45Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/csv-data
    type: Directory

