apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-postgres-job
spec:
  capacity:
    storage: 25Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/csv-data
    type: Directory

