apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-postgres-job
  namespace: name-db-lab
spec:
  storageClassName: ""
  volumeName: pv-for-postgres-job
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

