apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-name-db
  namespace: name-db-lab
spec:
  storageClassName: ""
  volumeName: pv-for-name-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Mi

