apiVersion: apps/v1
kind: Deployment
metadata:
  name: frn-app-node-js-deployment
  labels:
    app: frn-node-app-v2 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frn-node-app-v2
  template:
    metadata:
      labels:
        app: frn-node-app-v2
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nodejs-container
          image: localhost:5000/frn-app-nodejs-2025-07-09-a:v2
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_HOST
              value: "redis-service"

