apiVersion: apps/v1
kind: Deployment
metadata:
  name: frn-app-flask-deployment
  labels:
    app: frn-flask-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frn-flask-app-v2
  template:
    metadata:
      labels:
        app: frn-flask-app-v2
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: flask-container
          image: localhost:5000/frn-flask-v2-tejaris-2025-07-07:v2
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"

